"""Transparency labeller — planning §3.5 (exact copy).

Maps an (attribution, confidence, fused_p_ai) decision to the reader-facing
label: {level, badge, headline, body}. The body's `{pct}` is the likelihood of
the *predicted class* as a whole percent; the headline's strength word
("very likely" / "likely" / "possibly") comes from the §2.5 bands. All other
copy is the fixed string literals defined in §3.5.
"""

from provenance_guard.fusion import strength_word


def _predicted_class_pct(attribution: str, fused_p_ai: float) -> int:
    """Whole-percent likelihood of the predicted class (planning §3.5).

    For `ai`, that's `fused_p_ai`; for `human`, the complement.
    """
    if attribution == "ai":
        return round(fused_p_ai * 100)
    return round((1.0 - fused_p_ai) * 100)


def build_label(attribution: str, confidence: float, fused_p_ai: float) -> dict:
    """Return the §3.5 label variant for this decision."""
    # --- Variant C — Uncertain (no percentage is shown, planning §3.5) ---
    if attribution == "uncertain":
        return {
            "level": "uncertain",
            "badge": "Origin unclear",
            "headline": "We couldn't tell who wrote this.",
            "body": (
                "Our automated checks didn't find a strong enough signal to say "
                "whether this text was written by a person or generated by AI — "
                "the evidence was mixed or the passage was too short to judge. "
                "We're showing no attribution rather than guess. Creators can add "
                "a disclosure, and either side can appeal."
            ),
        }

    strength = strength_word(confidence)
    pct = _predicted_class_pct(attribution, fused_p_ai)

    # --- Variant A — High-confidence AI (level: "ai") ---
    if attribution == "ai":
        return {
            "level": "ai",
            "badge": "AI-generated (estimated)",
            "headline": f"This content was {strength} created with AI.",
            "body": (
                f"Our automated check estimates a {pct}% chance this text was "
                "generated by an AI tool, based on its writing style and language "
                "patterns. This is an estimate, not a certainty. If you're the "
                "creator and believe this is wrong, you can appeal."
            ),
        }

    # --- Variant B — High-confidence human (level: "human") ---
    return {
        "level": "human",
        "badge": "Human-written (estimated)",
        "headline": f"This content was {strength} written by a person.",
        "body": (
            f"Our automated check estimates a {pct}% chance this text was written "
            "by a human, based on its writing style and language patterns. This "
            "is an estimate, not a certainty. If you're the creator and believe "
            "this is wrong, you can appeal."
        ),
    }
