"""Signal 1 — Semantic analyzer (LLM judge via Groq).

Planning §1.3 and §2 "Signal 1": send the raw text to Groq with a system prompt
that forces a structured JSON verdict (`attribution`, `confidence`, `reason`),
then convert that verdict into a single probability the text is AI-written
(`p_ai_semantic`), per the mapping in §2.5:

    likely_ai   with confidence c -> p_ai = c
    likely_human with confidence c -> p_ai = 1 - c

The function never raises on a model/network failure: it degrades to a neutral,
`available: False` result so the pipeline can still respond (the structural
signal and fusion are designed to carry on without it).
"""

import json
import logging

from groq import Groq

from provenance_guard.config import Config

logger = logging.getLogger(__name__)

# The judge is constrained to emit exactly this JSON shape. Keeping the contract
# in the prompt (and asking for JSON object mode) is what makes the verdict
# machine-readable rather than prose we have to scrape.
_SYSTEM_PROMPT = """You are a forensic text analyst that judges whether a passage \
of text was written by a human or generated by an AI language model.

Judge ONLY by meaning-level character: tone, voice, semantic coherence, logical \
flow, specificity, and the tell-tale patterns of LLM prose (even hedging, \
generic balance, tidy summarizing conclusions). Do not count words or measure \
sentence lengths — that is a separate signal.

Respond with a single JSON object and nothing else, in exactly this form:
{
  "attribution": "likely_ai" | "likely_human",
  "confidence": <float between 0 and 1>,
  "reason": "<one concise sentence>"
}

"confidence" is how sure you are of the attribution you chose (0.5 = no idea, \
1.0 = certain). Be honest: reserve high confidence for clear cases."""

_USER_TEMPLATE = "Analyze this text:\n\n---\n{content}\n---"


def _neutral_result(reason: str) -> dict:
    """Result used when the signal can't produce a real verdict.

    `p_ai = 0.5` is deliberately uninformative so fusion treats it as "no
    opinion" rather than evidence in either direction.
    """
    return {
        "available": False,
        "p_ai": 0.5,
        "attribution": None,
        "confidence": None,
        "reason": reason,
    }


def _verdict_to_p_ai(attribution: str, confidence: float) -> float:
    """Map the LLM's (attribution, confidence) verdict to p_ai in [0, 1]."""
    confidence = max(0.0, min(1.0, float(confidence)))
    if attribution == "likely_ai":
        return confidence
    # likely_human
    return 1.0 - confidence


def analyze_semantic(text: str, client: Groq | None = None) -> dict:
    """Run the semantic signal on `text`.

    Returns a dict matching the `signals.semantic` shape in planning §4:
        {available, p_ai, attribution, reason}
    plus the raw `confidence` for the audit log. Always returns; never raises.
    """
    if not Config.GROQ_API_KEY:
        logger.warning("GROQ_API_KEY not set; semantic signal unavailable.")
        return _neutral_result("Semantic signal unavailable (no API key).")

    client = client or Groq(api_key=Config.GROQ_API_KEY)

    try:
        completion = client.chat.completions.create(
            model=Config.GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_TEMPLATE.format(content=text)},
            ],
            temperature=0,  # determinism matters for a forensic verdict
            response_format={"type": "json_object"},
            timeout=Config.GROQ_TIMEOUT_SECONDS,
        )
        raw = completion.choices[0].message.content
        verdict = json.loads(raw)
    except Exception as exc:  # noqa: BLE001 - degrade gracefully on any failure
        logger.exception("Semantic signal failed; degrading to neutral.")
        return _neutral_result(f"Semantic signal error: {exc}")

    attribution = verdict.get("attribution")
    confidence = verdict.get("confidence")
    reason = verdict.get("reason", "")

    if attribution not in ("likely_ai", "likely_human") or confidence is None:
        return _neutral_result("Semantic signal returned a malformed verdict.")

    p_ai = _verdict_to_p_ai(attribution, confidence)

    return {
        "available": True,
        "p_ai": round(p_ai, 4),
        "attribution": attribution,
        "confidence": round(float(confidence), 4),
        "reason": reason,
    }
